### ISSUE TITLE
SQL Query incompatible with version 1.1.2 of SurfTimer

### ISSUE THREAD

**Issue by BigTwoProduction** [surftimer/SurfTimer-Web#61]
Hello,

SurfTimer updated to 1.1.2 some of your query are not up-to-date in dashboard_player.php at line 113.
`SQL
SELECT COUNT(mapname) AS map_count, SUM(bonuses) AS map_bonuses_count, SUM(stages) AS map_stages_count FROM ck_maptier`
 for exemple this refer to non existing field in ck_maptier. So that create error like this :
`PHP Fatal error:  Uncaught Error: Call to a member function fetch_assoc() on bool in /var/www/surf/inc/pages/dashboard_player.php:113\nStack trace:\n#0 {main}\n  thrown in /var/www/surf/inc/pages/dashboard_player.php on line 113, referer: https://surf.xxx-xxx.fr/dashboard-player.php?id=xxxxxx`

Best regards,
Jordan.

**Comment by KristianP26** [comment]
Can you send me your SQL dump please?
Over discord or email.

**Comment by BigTwoProduction** [comment]
Hello,

I can if it is absolutely necessary but my database structure is the same as this :
[](https://github.com/surftimer/SurfTimer/blob/master/scripts/mysql-files/fresh_install.sql)

As you can see :
![image](https://user-images.githubusercontent.com/19799334/192778255-6520bbd4-2cbd-4e42-a5e7-8b49b629eaa0.png)

I remain available,
Best regards,
Jordan.

**Comment by KristianP26** [comment]
It will be easier for me when you create dump for me if is that possible.

**Comment by BigTwoProduction** [comment]
Hello,

I have just sent you the file by email.

Best Regards,
Jordan.

**Comment by KristianP26** [comment]
@BigTwoProduction does your db user have ability to ALTER TABLE?
Because i am adding 2 new colums:
https://github.com/surftimer/SurfTimer-Web/blob/d4bccd29ff3e8cd555e7410d16c426ac25fe67dc/inc/database.php#L14-L13
@Bara will be possible to add this into surftimer plugin?

**Comment by BigTwoProduction** [comment]
Hello,

@KristianP26 I can do what ever i want. I have my own server. I'm root on it so I've got all the privileges:)
Remaining available,
Jordan.

**Comment by KristianP26** [comment]
@BigTwoProduction but are you using connection with root user?

**Comment by KristianP26** [comment]
@BigTwoProduction bdv
running thesse queries will fix your problem:
https://github.com/surftimer/SurfTimer-Web/blob/d4bccd29ff3e8cd555e7410d16c426ac25fe67dc/inc/database.php#L14-L13
https://github.com/surftimer/SurfTimer-Web/blob/d4bccd29ff3e8cd555e7410d16c426ac25fe67dc/inc/database.php#L20
https://github.com/surftimer/SurfTimer-Web/blob/d4bccd29ff3e8cd555e7410d16c426ac25fe67dc/inc/database.php#L27
https://github.com/surftimer/SurfTimer-Web/blob/d4bccd29ff3e8cd555e7410d16c426ac25fe67dc/inc/database.php#L34

**Comment by BigTwoProduction** [comment]
> @BigTwoProduction but are you using connection with root user?

Non Read only, I will run these queries with root account

**Comment by KristianP26** [comment]
> > @BigTwoProduction but are you using connection with root user?
> 
> Non Read only, I will run these queries with root account

That's the problem.

**Comment by BigTwoProduction** [comment]
Initially the problem was not the read only account ;)
But I'm glad to see that it works now.
Suggestion instead of ADD why not use ADD IF NOT EXISTS ?

**Comment by Bara** [comment]
>  @Bara will be possible to add this into surftimer plugin?

No, why we should add columns which will never used officially?
