### ISSUE TITLE
Flags picture is in error 404

### ISSUE THREAD

**Issue by BigTwoProduction** [surftimer/SurfTimer-Web#62]
Hello,

I notice that the flags are not displayed.
In cause the name of the files are in capital letters whereas in the folder in github and on the server side they are in lower case.
![image](https://user-images.githubusercontent.com/19799334/194542815-4b88f6d0-c6d4-4ebc-bbfa-8c728696e6ac.png)

![image](https://user-images.githubusercontent.com/19799334/194543036-efd1b762-1987-49ff-ab17-94f891e9871a.png)

Sincerely,
Jordan.

**Comment by KristianP26** [comment]
Fixed by: https://github.com/surftimer/SurfTimer-Web/commit/40532cbfc813a4aefb24c22063f7de2dc4da852d
