### ISSUE TITLE
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted

### ISSUE THREAD

**Issue by joscha0** [surftimer/SurfTimer-Web#64]
When opening a map with a large .bsp file the page is blank and I get the following error in the logs:
`FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 77611008 bytes) in /var/www/web/inc/functions.php on line 195"`

Setup: ngnix + fastcgi

**Comment by KristianP26** [comment]
Can you provide me your fastdl link and map name?

**Comment by joscha0** [comment]
fastdl link: http://fastdl-go.surf0.net/csgo/maps/
map name: This happened for example for surf_whiteout
